export const GET_CATEGORIES_REQUEST = 'GET_CATEGORIES_REQUEST';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE';

export const GET_DOCS_REQUEST = 'GET_DOCS_REQUEST';
export const GET_DOCS_SUCCESS = 'GET_DOCS_SUCCESS';
export const GET_DOCS_FAILURE = 'GET_DOCS_FAILURE';

export const GET_DOC_REQUEST = 'GET_DOC_REQUEST';
export const GET_DOC_SUCCESS = 'GET_DOC_SUCCESS';
export const GET_DOC_FAILURE = 'GET_DOC_FAILURE';